### ISSUE TITLE
why snapshot page was removed?

### ISSUE THREAD

**Issue by fsdrw08** [vyos/community.vyos.net#17]
I found that the snapshot link was 404 https://vyos.net/get/snapshots/ and this is the related commit
https://github.com/vyos/community.vyos.net/commit/197323a832082991aec0c287ee6a5b1620f6067c

we cannot download snapshot iso now, any other way to download snapshot image now?

**Comment by andamasov** [comment]
Snapshots were outdated by now
you can build images from the source

**Comment by dmbaturin** [comment]
Those snapshots were serving a specific purpose: to provide semi-stable pre-release 1.3.0 images to those who wanted to test them, in a time when the only way to ensure that an image isn't horribly broken was to test it manually. And, yes, as pre-release images from almost a year ago, they were very outdated already.

You can [build](https://docs.vyos.io/en/equuleus/contributing/build-vyos.html#build-iso) recent 1.3.x images from source or get them from [OpenCollective](https://opencollective.com/vyos) for a donation.
